### PR TITLE
Suggestion: place the logo on the header

### PR DESCRIPTION
**Pull request by igoogolx**
It's **not** a feature or bug, but a suggestion. Can we place the logo on the app header? :)

image

### CODE REVIEW

**Comment by GeoffreyChen777** [comment]
Sure, but I would suggest using these two:

app/renderer/assets/logo-light.png
app/renderer/assets/logo-dark.png

And, I think we can also add a title text `Paperlib` with this icon.

layout:

```
icon   [space]   Paperlib       |
                                |           <-- I think we should add a little more space here to separate the icon title from the section below
Library  Feeds                  |

```

**Comment by igoogolx** [comment]
Would this version work for you?

**Light**:
image

**Dark**:
image

**Comment by GeoffreyChen777** [comment]
Let's merge it into another branch. I will make some small adjustments.

**Comment by GeoffreyChen777** [comment]
Emm. just merge it to the main and I make some small adjustments later.

**Pull request merged**
