### PR TITLE
Features/255 support more hotkeys

### PR DESCRIPTION
**Pull request by igoogolx**
Implement #255.
**Note**: It's not a small change. We need more tests before merging. Could you plz help with that? @GeoffreyChen777

### CODE REVIEW

**Comment by igoogolx** [comment]
If there are any issues, feel free to let me know.

**Comment by GeoffreyChen777** [comment]
Sure I will test that.

BTW, this PR #448 is also a huge change. It would be good if you can help me to test. I’ve tested on my side. Everything looks good.

**Comment by igoogolx** [comment]
> Sure I will test that.
> 
> BTW, this PR #448 is also a huge change. It would be good if you can help me to test. I’ve tested on my side. Everything looks good.

Thanks and I will test #448.

**Comment by GeoffreyChen777** [comment]
I fixed a bug of the meta key on macOS.

Now everything looks good to me.

**Review by GeoffreyChen777 — APPROVED** [review]

**Pull request merged**
