### PR TITLE
[Feature] Add links to webpage for papers with arxiv and doi

### PR DESCRIPTION
**Pull request by charlieJ107**
This PR implemented #469 

I added two link button that open the system default external browser to open the arxiv or doi link based on the `arxiv` and `doi` properties in `PaperEntity`. These two buttons only shows when these two properties existed. 

I also remove the `formatOnSave` settings in `.vscode/settings.json` because the format behaviour may vary on different platform, which may mess up the format of entire file.

### CODE REVIEW

**Comment by charlieJ107** [comment]
FYI, here's some screenshot: 

image

image

**Comment by GeoffreyChen777** [comment]
It looks good. I’m thinking what about merging this with the source code section to get a section called ‘online resource’?

**Comment by charlieJ107** [comment]
> It looks good. I’m thinking what about merging this with the source code section to get a section called ‘online resource’?

Should it be in the same slot with the publisher (slot 1) or at the bottom of the paper details (slot 3)?

**Comment by charlieJ107** [comment]
> It looks good. I’m thinking what about merging this with the source code section to get a section called ‘online resource’?

Should it be in the same slot with the publisher (slot 1) or at the bottom of the paper details (slot 3)?

**Comment by GeoffreyChen777** [comment]
We leave the publication text in the publication section. And we move the link buttons, such as the ‘DOI’ one in the screenshot to the source code section and we rename the source code section to ‘online resource’ section.

**Comment by charlieJ107** [comment]
Now it's like this: 

image

**Comment by GeoffreyChen777** [comment]
Looks good.👍🏻 thanks.

I will review the code once I back from my trip.

**Review by GeoffreyChen777 — APPROVED** [review]

**Comment by GeoffreyChen777** [comment]
I fixed some bugs [9b6c02f](https://github.com/Future-Scholars/paperlib/pull/475/commits/9b6c02f519975b2b6cfe680147f4767b27a7076c) , now everything looks good to me.

**Pull request merged**
