### PR TITLE
Feat: BibItem export #458

### PR DESCRIPTION
**Pull request by omrihaber**
It seems to work, I have some code standards/contribution questions:
1. commit messages - seems to follow conventional commits- does capitalization matter? i.e. Feat or feat.
2. string utils - i used a capitalized function in the code i added, i saw other places defining the same function should i consolidate the function to some util or at base/string?
3. tests - some of the convertion logic im not sure I placed it in the correct place or it should be in some service and if so maybe i can add tests?
4. The conversion logic i took from the repo that was suggested in #458  added a comment there pointing to the file i took the code from, is it better to use a different comment format or remove it? if you know of a better/more elegant way to convert it let me know il make changes as needed

### CODE REVIEW

**Comment by JeffStrongman** [comment]
omg this is exactly what i was looking for. boy i sure do hope this gets resolved asap :)

**Comment by GeoffreyChen777** [comment]
@omrihaber Hi I think it’s unnecessary to manually construct the body of bibitems, as we need to support different CSLs.

you can use the method `exportPlainText` for that.

**Comment by omrihaber** [comment]
so something like this?
```
`\\bibitem{${authors[0].given}} ${exportPlainText(cite)}`
```

**Comment by GeoffreyChen777** [comment]
use `exportBibTexKey` for the id.

**Comment by omrihaber** [comment]
Changed to use exportPlainText and exportBibTexKey.
exapmle output:
\bibitem{gu2021pointer} Gu, S., & Yao, H. (2021). Pointer Network Based Deep Learning Algorithm for the Maximum Clique Problem. In International Journal on Artificial Intelligence Tools (Vol. 30, Issue 01, p. 2140004). World Scientific Pub Co Pte Lt. https://doi.org/10.1142/S0218213021400042

**Review by GeoffreyChen777 — APPROVED** [review]

**Pull request merged**
