### PR TITLE
fix: unexpected preview shortcut in edit view

### LINKED ISSUE #453: [BUG] Some bugs when editing metadata.
**Describe the bug**
1. can not press arrow key (↑, ↓, ←, →) when make notes.
2. If press "`<space>`" when editing metadata, the preview mode is triggered.

**Screenshots or Log**

screenshot for problem 1

image

screenshot for problem 2: 

image

**System (please complete the following information):**
 - OS: macos 
 - Paperlib Version: 3.0.5

### PR DESCRIPTION
**Pull request by igoogolx**
Fix #453.

### CODE REVIEW

**Comment by GeoffreyChen777** [comment]
I remember why we have this code.

If we remove it, it will cause a new bug.

see:

https://github.com/Future-Scholars/paperlib/pull/408

**Comment by igoogolx** [comment]
> I remember why we have this code.
> 
> If we remove it, it will cause a new bug.
> 
> see:
> 
> #408

I see. It is a default shortcut for Chrome.

image

**Comment by GeoffreyChen777** [comment]
Yes, Electron also has this default shortcut.

**Comment by igoogolx** [comment]
We need a better way. Will try to fix it in #447.

**Pull request closed without merging**
