### PR TITLE
[Feature] Export Data as CSV

### PR DESCRIPTION
**Pull request by charlieJ107**
### Description
Add CSV export options when exporting paper data. 

### Solution / Changes
- [x] Add CSV export function to `ReferenceService`. This function handles the paper entities to export and build the CSV file content as string
- [x] Add CSV export functionality to `ContextMenuService`. This function fires the CSV export event when user clicks the export option in context menu. This also includes changes to the interfaces that are exported as PLMainAPI. 
- [x] Add CSV export option to main view context menu when right click on selected paper(s).  

### Related Issue/PR
#323

### CODE REVIEW

**Comment by GeoffreyChen777** [comment]
The method in `ReferenceService` looks good.

Let's add a new section in `preference view - export tab` to export the entire library to a `.csv` file. Just use the `PaperService` with an empty filter to load all papers.

**Comment by charlieJ107** [comment]
> The method in `ReferenceService` looks good.
> 
> Let's add a new section in `preference view - export tab` to export the entire library to a `.csv` file. Just use the `PaperService` with an empty filter to load all papers.

Do you think we need to allow users to choose the place that saving the new `.csv` file? Or we can just export to a default directory (e.g. Desktop or `$HOME`) with a default file name. 

Obviously the latter one will be simpler. Allow users to choose the saving file path means either:
 (1) we need to implement a custom window to accept the path input by users then save the file with the filesystem service call 
or 
 (2) we need to invoke an external RPC call to ask the main process to invoke an OS level file saving dialog.

**Comment by GeoffreyChen777** [comment]
> > The method in `ReferenceService` looks good.
> > Let's add a new section in `preference view - export tab` to export the entire library to a `.csv` file. Just use the `PaperService` with an empty filter to load all papers.
> 
> Do you think we need to allow users to choose the place that saving the new `.csv` file? Or we can just export to a default directory (e.g. Desktop or `$HOME`) with a default file name.
> 
> Obviously the latter one will be simpler. Allow users to choose the saving file path means either: (1) we need to implement a custom window to accept the path input by users then save the file with the filesystem service call or (2) we need to invoke an external RPC call to ask the main process to invoke an OS level file saving dialog.

I think we can let the user select a folder for exporting. The export filename can be generated such as `CSV_timestamp.csv`

To show a path selecting dialog, we have an existing component for that, please refer to:

https://github.com/Future-Scholars/paperlib/blob/881134a15918f572ea6b5afc3a1930997e0e3ca9/app/renderer/ui/preference-view/components/path-picker.vue#L1

For the usage demo, you can check here:

https://github.com/Future-Scholars/paperlib/blob/881134a15918f572ea6b5afc3a1930997e0e3ca9/app/renderer/ui/preference-view/general-view.vue#L105

It's very easy to get the user's selected path. After that, you can construct a `.csv` path and write exported content into it.

**Review by GeoffreyChen777 — APPROVED** [review]
I enhanced your function to export complex objects.

I just simply transform them into string like: Tag1;Tag2.

**Pull request merged**
